# fly.toml app configuration file generated for phalanx-weathered-rain-7874 on 2026-04-26T14:45:40-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phalanx-weathered-rain-7874'
primary_region = 'jnb'

[build]
  dockerfile = 'Dockerfile'

[env]
  BIND_ADDR = '::'
  BIND_PORT = '7946'
  DATA_DIR = '/data'
  DEBUG_ADDR = '[::]:8080'
  ELECTION = '20'
  GRPC_ADDR = '[::]:9000'
  HEARTBEAT = '5'
  TICK_MS = '200'

[[mounts]]
  source = 'phalanx_data'
  destination = '/data'

[[services]]
  protocol = 'tcp'
  internal_port = 9000
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 5

  [[services.ports]]
    port = 9000

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 8080

  [[services.http_checks]]
    interval = '15s'
    timeout = '5s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
